### ISSUE TITLE
Android-Proguard aktivieren

### ISSUE THREAD

**Issue by MoritzLi** [LCA311/leo-app#28]

**Comment by MoritzLi** [comment]
https://developer.android.com/studio/build/shrink-code.html
Aber erst ganz am Ende

**Comment by LCA311** [comment]
Ich weiß, ich hab mir da vor einiger Zeit mal n Bookmark gemacht.

**Comment by LCA311** [comment]
This issue was moved to LCA311/leoapp-sources#12
