### ISSUE TITLE
Beschreibungen für Gruppen

### ISSUE THREAD

**Issue by LCA311** [LCA311/leo-app#37]
Da im LeoApp Chatitemlayout der Chatname nicht zentriert ist, bietet es sich doch an, eine optionale Beschreibung der Gruppe anzuzeigen (analog zu Einzelchats).

![alt text](https://raw.githubusercontent.com/LCA311/leo-app/master/chats.jpg)

**Comment by LCA311** [comment]
Meinungen?

**Comment by MoritzLi** [comment]
Verstehe ich halt nicht so richtig

**Comment by LCA311** [comment]
Man kann als Gruppenmitglied eine Gruppenbeschreibung angeben, die dann im Listing angezeigt wird. Bei WhatsApp habe ich beispielsweise 20 Gruppen, von denen ich nicht weiß, wozu ich da drin bin. Gleichzeitig sieht dann das Design gleich viel besser aus, weil dann unter den Gruppennamen noch was steht.

**Comment by MoritzLi** [comment]
also quasi Notizen

**Comment by MoritzLi** [comment]
bin pro

**Comment by LCA311** [comment]
Ich hatte er an eine allgemeine Beschreibung gedacht, die für alle User dieselbe ist

**Comment by LCA311** [comment]
*eher
