### ISSUE TITLE
Messenger: Suchen und Sortieren

### ISSUE THREAD

**Issue by Sir-M** [LCA311/leo-app#40]
Die Suchfunktion sollte nicht als einzelner Tab da stehen, da er sonst gleichwertig ist mit den Kontakten und den Chats ist, dabei ist er bloß ein Unterpunkt in den Kontakten. 
Also : 
FAB in Kontakten
oder
Such-Icon in Toolbar wenn auf dem Kontakt-Tab
oder
... _Vorschläge erwünscht._

Die Suche könnte außerdem **in der Toolbar selbst** erfolgen, da die Ergebnisse direkt sind.

Sortieren:
Da das Feature bei einer Suche mit direkten Ergebnissen nicht zwingend notwendig ist, muss es als erweiterte Suche zu Verfügung stehen. Entweder zum Ausklappen unter dem EditText der Suche oder mit Icon, der zu sowas weiterleitet:

![image](https://user-images.githubusercontent.com/13520101/29499859-2f55faba-861a-11e7-9ac1-7a3d336ea6ee.png)

Sollte halt intuitiv bleiben.

**Comment by LCA311** [comment]
Dafür!

**Comment by LCA311** [comment]
Radikal
