### ISSUE TITLE
Graph des Stimmungsbarometer unkennntlich

### ISSUE THREAD

**Issue by Sir-M** [LCA311/leo-app#41]
Die Farben der Graphen und der einzelnen Abschnitten sind teilweise noch zu ähnlich und die Graphlinien zu dünn, um sie von den Abschnitten zu unterscheiden.

Vorschlag: Die Farben der Abschnitte entfernen/ ggf. gestrichelt um den Kontrast zu verstärken

Entweder ist die Steigerung und die Minderung so oder so abzulesen, andernfalls müssen die geeigneten Smileys als Legende an die Abschnitte hinzugefügt werden.

**Comment by MoritzLi** [comment]
Wtf
