### ISSUE TITLE
Um 00:00h werden die Notifications für die gesamte Minute dauergesendet

### ISSUE THREAD

**Issue by LCA311** [LCA311/leo-app#43]
Sofern die Notifications auf diese Uhrzeit eingestellt sind, werden so viele Notifications gesendet, dass sich Android aufhängt. In der Notificationliste bleibt jedoch nur die der Essensbestellung.

**Comment by LCA311** [comment]
In Progress

**Comment by Sir-M** [comment]
Der Bug bezieht sich nicht auf die in den LeoApp Einstellungen angebene Uhrzeit, sondern wiederholt sich immer um 0h. 
Menge der Notifications haben abgenommen und App muss nicht mehr gekillt werden.

**Comment by LCA311** [comment]
Sollte gefixt sein.
