### ISSUE TITLE
Coming Soon

### ISSUE THREAD

**Issue by Sir-M** [LCA311/leo-app#47]
Die "Coming Soon" Kacheln bitte nicht so auffällig in die Mitte der anderen platzieren und nicht rot färben. Sieht so aus als wäre die hälfte der App nicht fertig

**Comment by LCA311** [comment]
Wie sonst? Grau? Und das ist alphabetisch geordnet btw.

**Comment by Sir-M** [comment]
Ja, grau. Und das mit dem alphabetisch geordnet klappt halt nicht wenn da nur "Coming Soon" steht. Ich würde die nach unten packen, wenn nicht sogar eine eigene, einzelne Coming Soon Kachel mit den Änderungen, die wir vorhaben.

**Comment by MoritzLi** [comment]
Gar keine Coming Soon Kachel ?

**Comment by LCA311** [comment]
Lass mich das mal machen, ich hab da ne Idee

**Comment by LCA311** [comment]
Fertig.

**Comment by MoritzLi** [comment]
Ich würde Nachhilfebörse wieder Coming Soon machen
