### ISSUE TITLE
Stundenplan - Fehler beim Ausgrauen

### ISSUE THREAD

**Issue by LCA311** [LCA311/leo-app#48]
Bei der Kursauswahl im Stundenplan werden Stundenkonflikte nicht  (immer?) ausgegraut. Beispiel: Deutsch G1  und Mathe G3.

**Comment by MoritzLi** [comment]
Den Fehler habe ich in meiner Version nicht

**Comment by LCA311** [comment]
Dann nimm die Neueste

**Comment by MoritzLi** [comment]
Ich wollte nur sagen, dass der Fehler erst später entstanden ist...
