### ISSUE TITLE
Anzeigefehler Stundenplannotification

### ISSUE THREAD

**Issue by LCA311** [LCA311/leo-app#50]
In der Notification des Stundenplans werden zurzeit Freistunden mit angezeigt, was zu einer Aneinanderreihung von Kommas führt  (siehe unten).

![e360b6aa-01ce-4ca3-9a1d-aabe16c0d765](https://user-images.githubusercontent.com/22426881/29745535-b4a52d9c-8abd-11e7-8ae4-9e08361ae572.jpg)

![085418b9-63d3-4341-99a4-c63f46b59b3b](https://user-images.githubusercontent.com/22426881/29745534-ad7a72f2-8abd-11e7-855c-148ea11b329c.jpg)

**Comment by Sir-M** [comment]
, , , ,
