### ISSUE TITLE
Notifications mit ContentIntent schliessen die App

### ISSUE THREAD

**Issue by MoritzLi** [LCA311/leo-app#51]
Wenn die Notification eine Activity öffnet und man von dieser auf die Startseite wechseln will, wird die aktuelle Activity geschlossen, aber weil MainActivity noch nicht auf gerufen wurde, wird die App geschlossen

**Comment by MoritzLi** [comment]
Keinen Bock das zu fixen

**Comment by LCA311** [comment]
In Progress

**Comment by LCA311** [comment]
Fixed.
