### ISSUE TITLE
Schulhomepageartikel in Schwarzes Brett integrieren

### ISSUE THREAD

**Issue by LCA311** [LCA311/leo-app#62]
Da die Homepage selten von Schülern genutzt wird, und sich das mit dem digitalen Klausurplan nicht verbessern wird, wäre es doch sinnvoll, neue Artikel am digitalen Schwarzen Brett zu hinterlegen. Mit Titel und kurzer Beschreibung + Weiterleitung auf kompletten Artikel.

**Comment by MoritzLi** [comment]
Sicher?

**Comment by LCA311** [comment]
Ja, sonst hätte ich es nicht vorgeschlagen. Es gibt ja nicht allzu häufig neue Artikel und wenn's jemanden wirklich stört kann man das ja in den Einstellungen ausschalten.

**Comment by bormel** [comment]
damit werden aber wichitge Informationen mit irgendwelchen Artikeln über die letzte Unterstufenparty vermischt. Das wäre ungünstig.

**Comment by LCA311** [comment]
Man könnte Homepageartikel immer am Ende der Liste anzeigen; generell wäre es schön wenn man besonders wichtige Informationen am Anfang der Seite hätte.

**Comment by bormel** [comment]
Ich würde es trennen. Das schwarze Brett ist nunmal keine Homepage. Das eine repräsentiert interne Infos , das andere "Öffentlichkeitsarbeit". 
Ich könnte mir allenfalls vorstellen, dass es ein Feature gibt, welches dem Nutzer mitteilt, dass es Neuigkeiten auf der HP gibt (inkl. Link). Aber auch diese nicht im Bereich des schwarzen Bretts. Vielleicht ausschließlich als Benachrichtigung.
