### ISSUE TITLE
Notifications canceln, wenn man App manuell startet

### ISSUE THREAD

**Issue by LCA311** [LCA311/leo-app#63]
Zurzeit bleiben die Notifications in der Statusbar oder werden gesendet, während man den Messenger benutzt

**Comment by Sir-M** [comment]
Ist das nicht im Moment bei allen Notifications noch so?

**Comment by MoritzLi** [comment]
Sollte gefixt sein aber ich schließe das erstmal noch nicht

**Comment by MoritzLi** [comment]
also beim messenger funktioniert das jetzt
