### ISSUE TITLE
Tutorialbildschirm vervollständigen und integrieren

### ISSUE THREAD

**Issue by LCA311** [LCA311/leo-app#65]
-

**Comment by Sir-M** [comment]
1. Card: LeoApp
2. Card: Abläufe vereinfachen (Essensbons, Klausurplan) 
3. Card: Kommunikation verbessern (Messenger, Schwarzes Brett) 
evtl. noch eine Card mehr, keine Ahnung...
Auf jeden Fall wird das kein richtiges Tutorial glaube ich
