### ISSUE TITLE
Umlaute im Schwarzen Brett werden nicht angezeigt

### ISSUE THREAD

**Issue by LCA311** [LCA311/leo-app#81]
In PHP/JS durch Zeichenfolge ersetzen und in der App entsprechend Umlaute einsetzen?

**Comment by Sir-M** [comment]
In den Lehrerkürzeln im Stundenplan auch nicht.

**Comment by MoritzLi** [comment]
Ich glaube, das ist nicht mehr aktuell. Nur manche Datenbankeinträge sind noch mit falschen Umlauten
