### ISSUE TITLE
Absturz Stundenplan

### ISSUE THREAD

**Issue by Sir-M** [LCA311/leo-app#83]
Stundenplan kann nach Ausfüllen nicht mehr geöffnet werden, kurz vorher die Freitstundennotiz geändert. Notiz ist jetzt null(?)
Fehlermeldung:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at de.slg.stundenplan.StundenplanActivity$StundenAdapter.getView(StundenplanActivity.java:280)

**Comment by MoritzLi** [comment]
Dann könntest du das doch mal beheben
